# Use the official Node.js image as the base image
FROM node:20.15-slim

# Install git
RUN apt-get update && apt-get install -y git

WORKDIR /usr/src/client

COPY ./package.json .

# Install dependencies
RUN npm install next react react-dom -g
RUN npm install

# Copy the rest of the application code to the working directory

# Expose the port that the application will run on
EXPOSE 3001
